AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Multi-Lambda deployment via SAM (code + environment variables)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256

Resources:
  FunctionOne:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda1
      CodeUri: src/lambda1/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ENV: dev
          API_BASE: https://api.example.com
          FEATURE_FLAG_X: "true"
      # # Optional API trigger for quick testing:
      # Events:
      #   GetOne:
      #     Type: Api
      #     Properties:
      #       Path: /one
      #       Method: GET

  FunctionTwo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda2
      CodeUri: src/lambda2/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ENV: dev
          DB_TABLE: users
          LOG_LEVEL: INFO
      # # Optional API trigger:
      # Events:
      #   GetTwo:
      #     Type: Api
      #     Properties:
      #       Path: /two
      #       Method: GET